services:
  users-db:
    image: postgres:16
    container_name: krutobank-users-db
    environment:
      POSTGRES_DB: kruto_users
      POSTGRES_USER: kruto_users
      POSTGRES_PASSWORD: kruto_users_password
    ports:
      - "54321:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data

  accounts-db:
    image: postgres:16
    container_name: krutobank-accounts-db
    environment:
      POSTGRES_DB: kruto_accounts
      POSTGRES_USER: kruto_accounts
      POSTGRES_PASSWORD: kruto_accounts_password
    ports:
      - "54322:5432"
    volumes:
      - accounts-db-data:/var/lib/postgresql/data

  credits-db:
    image: postgres:16
    container_name: krutobank-credits-db
    environment:
      POSTGRES_DB: kruto_credits
      POSTGRES_USER: kruto_credits
      POSTGRES_PASSWORD: kruto_credits_password
    ports:
      - "54323:5432"
    volumes:
      - credits-db-data:/var/lib/postgresql/data

volumes:
  users-db-data:
  accounts-db-data:
  credits-db-data:
